import { notFound, redirect } from "next/navigation";
import { dues, students } from "@/lib/db";
import { getCurrentTutor } from "@/lib/auth";
import { monthLabel } from "@/lib/messages";

export const dynamic = "force-dynamic";

export default async function ReceiptPage({
  params,
}: {
  params: { id: string };
}) {
  const tutor = await getCurrentTutor();
  if (!tutor) redirect("/login");

  const due = await dues.byId(params.id);
  const student = due ? await students.byId(due.studentId) : undefined;
  if (!due || !student || student.tutorId !== tutor.id || due.status !== "PAID") {
    notFound();
  }

  const from = tutor.businessName || tutor.name;

  return (
    <main className="mx-auto max-w-md px-6 py-10 print:py-2">
      <div className="card anim-scale-in p-8 print:border-0 print:shadow-none">
        <div className="flex items-center justify-between">
          <h1 className="font-display text-lg font-semibold">{from}</h1>
          <span className="chip border border-emerald-200 bg-emerald-50 font-semibold text-emerald-700">
            PAID
          </span>
        </div>
        <p className="mt-1 text-xs text-slate-400">
          Fee Receipt · #{due.id.slice(-8).toUpperCase()}
        </p>

        <dl className="mt-6 space-y-3 text-sm">
          <div className="flex justify-between">
            <dt className="text-slate-500">Student</dt>
            <dd className="font-medium">{student.name}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Month</dt>
            <dd className="font-medium">{monthLabel(due.month)}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Amount</dt>
            <dd className="font-bold">₹{due.amount.toLocaleString("en-IN")}</dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Paid on</dt>
            <dd className="font-medium">
              {due.paidAt
                ? new Date(due.paidAt).toLocaleDateString("en-IN", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                  })
                : ""}
            </dd>
          </div>
          <div className="flex justify-between">
            <dt className="text-slate-500">Method</dt>
            <dd className="font-medium">
              {due.paymentMethod === "RAZORPAY" ? "Online (Razorpay)" : "UPI / Cash"}
            </dd>
          </div>
        </dl>

        <p className="mt-8 border-t border-dashed border-slate-200 pt-4 text-center text-xs text-slate-400">
          Generated by FeeSaathi
        </p>
      </div>
      <p className="mt-4 text-center text-sm text-slate-400 print:hidden">
        Use your browser&apos;s Print → Save as PDF to share this receipt.
      </p>
    </main>
  );
}
